package tech.jhavidit.remindme.util


const val TAG = "tag"
const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 201
const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 202
const val LOCATION_PERMISSION_INDEX = 0
const val BACKGROUND_LOCATION_PERMISSION_INDEX = 1
